# Class 7. More exam prep

# Imports

In [1]:
import pandas as pd
import numpy as np

from IPython.core.display import HTML #for the fancy table formatting
table_css = 'table {align:left;display:block} '
HTML('<style>{}</style>'.format(table_css))

# Exercise 1. Primitive calculator

In this task you are to implement a simple calculator. It has to support at least 3 operations:

One elementary operation:
1. addition (+)
2. subtraction (-)

One scaling operation:
1. multiplication (*)
2. division (/)
3. power (**)

One type-specific operation: (for your calculator it should work on integers only)
1. integer division (//)
2. modulus (%)


Your function must account for possible errors. If the computation yields an error, you should output it to the user and log it into a special ```err.txt``` file\
The function must request user input or it can accept an expression as its argument. Name the function ```calc```

Example of your function's flow:

**Example 1**

Input:

    Enter the expression: 1 * 5

Output:

    Result: 5


**Example 2**

Input:

    Enter the expression: 1 / 0

Output:

    Error! Division by zero, computation impossible. This action has been logged

err.txt:

    1 / 0 : Division by zero

In [44]:
def calc()->None:

    #read user input
    user_input = input('Enter the expression: ')
    # print(user_input)
    user_input_log = user_input
    

    try:

        user_input = user_input.replace(' ','')
        
        if '+' in user_input:
            
            user_input = user_input.split('+')
            # print(user_input)
            
            # user_input = list(user_input) 
            # print(user_input)
            
            num1 = int(user_input[0])
            num2 = int(user_input[-1])
        
            # print(num1, num2)
            # print(type(num1), type(num2))
            print(num1 + num2)
    
    
        if '*' in user_input:
            
            user_input = user_input.split('*')
            # print(user_input)
            
            user_input = list(user_input) 
            # print(user_input)
            
            num1 = int(user_input[0])
            num2 = int(user_input[-1])
        
            # print(num1, num2)
            # print(type(num1), type(num2))
            print(num1 * num2)
    
        if '//' in user_input:
            
            user_input = user_input.split('//')
            # print(user_input)
            
            user_input = list(user_input) 
            # print(user_input)
            
            num1 = int(user_input[0])
            num2 = int(user_input[-1])
        
            # print(num1, num2)
            # print(type(num1), type(num2))
            print(num1 // num2)

    except:
        print(user_input, user_input_log)
        with open('err.txt', 'a') as file:
            file.write(user_input_log)
            file.write('\n')
        
        print('Error!')

calc()

Enter the expression:  14124 + 12412


26536


# Exercise 2. Calculator 2.0

Now instead of doing simple calculations, your task is to make a calculator that would work with 1D arrays.\
The input to your function is a single 2D array ```X``` of shape ```(n, m)```, where ```n``` is the number of variables and ```m``` is the shape of every variable\
In this version you are only to implement 4 fundamental operations:
1. ```+```
2. ```-```
3. ```*```
4. ```/```

Additionally, your function must request an input of an expression of this format:

    x0 * x1 / x2 - x3

This line means that we take the 1'st row of the ```X``` and multiply it by the second row and divide the result by the third row, finally subtracting the values from the fourth row.\
All operations are elementwise:

    [1, 2] - [0, 2] = [1, 0]

Your function must of course account for the order of operations, thus both ```-``` and ```+``` go after ```*``` and ```/```.\
Consider that the input expressions **don't** have any braces\
The function should return the result of the expression (not output it on the screen)

**Example 1**

Inputs:

    X = [[1, 0], [2, 1], [3, 5]]

    Enter the expression: x0 - x2 * x1

Output:

    [-5, -5]

In [78]:
def calc2(X: np.ndarray) -> np.ndarray:

    expr = input('Enter the expression: ')
    print(f'expr: {expr}')
    expr = expr.split(' ')
    print(f'expr new {expr}')
    ops = expr[1::2]
    print(f'operations: {ops}')

    print('Starting loop...')

    add_sub = []
    mult_div = []
    set_add_sub = {'-', '+'}
    for idx, x in enumerate(expr[::2]):
        idx *= 2 

        if idx == 0 and expr[idx + 1] in set_add_sub:
            add_sub.append(idx)
        
        elif idx == len(expr)-1 and expr[idx - 1] in set_add_sub:
            add_sub.append(idx)
        
        elif expr[idx - 1] in set_add_sub and expr[idx + 1] in set_add_sub:
            add_sub.append(idx)
        
        else:
            mult_div.append(idx)

    # addition and subtraction
    sm = np.zeros(X.shape[1])
    for i in add_sub:
        if expr[i-1] == '-':
            sm -= X[i]
        else:
            sm += X[i]

    #multiplication and division
    mult_div = np.array(mult_div)
    rs = mult_div - np.concatenate(([0], mult_div[:-1]), axis=0)
    print(f'add_sub: {add_sub}\n\nmult_div: {mult_div}')

    mult_sm = 0
    mult = 1
    
    for idx, r in enumerate(rs):

        if r > 2:
            sign = int(f'{expr[idx*2 - 1]}1')
            mult = 1
        
        if r == 2:
            
            if expr[idx*2-1] not in {'*', '/'}:
                mult = X[mult_div[idx // 2]]
            elif expr[idx*2-1] == '/':
                mult /= X[mult_div[idx // 2]]
            else:
                mult *= X[mult_div[idx // 2]]

        if idx != len(rs) - 1 and rs[idx+1] > 2:
            mult_sm += mult * sign

    return mult_sm + sm        
            
X = np.random.randint(1, 5, (3,3))
print(X)
calc2(X)

[[4 4 1]
 [2 3 4]
 [1 4 2]]


Enter the expression:  x0 - x1 * x2


expr: x0 - x1 * x2
expr new ['x0', '-', 'x1', '*', 'x2']
operations: ['-', '*']
Starting loop...
add_sub: [0]

mult_div: [2 4]


array([4., 4., 1.])

# Exercise 3. Confirmation Rate

Table: ```signups```


| Column Name    | Type     |
|----------------|----------|
| user_id        | int      |
| time_stamp     | datetime |

user_id is the column of unique values for this table.\
Each row contains information about the signup time for the user with ID user_id.
 

Table: ```confirmations```


| Column Name    | Type     |
|----------------|----------|
| user_id        | int      |
| time_stamp     | datetime |
| action         | ENUM     |

(user_id, time_stamp) is the primary key (combination of columns with unique values) for this table.\
user_id is a foreign key (reference column) to the Signups table.\
action is an ENUM (category) of the type ('confirmed', 'timeout')\
Each row of this table indicates that the user with ID user_id requested a confirmation message at time_stamp and that confirmation message was either confirmed ('confirmed') or expired without confirming ('timeout').
 

The confirmation rate of a user is the number of 'confirmed' messages divided by the total number of requested confirmation messages. The confirmation rate of a user that did not request any confirmation messages is 0. Round the confirmation rate to two decimal places.

Write a solution to find the confirmation rate of each user.

Return the result table in any order.

The result format is in the following example.

 

Example 1:

Input: \
```signups``` table:

| user_id | time_stamp          |
|---------|---------------------|
| 3       | 2020-03-21 10:16:13 |
| 7       | 2020-01-04 13:57:59 |
| 2       | 2020-07-29 23:09:44 |
| 6       | 2020-12-09 10:39:37 |

```confirmations``` table:

| user_id | time_stamp          | action    |
|---------|---------------------|-----------|
| 3       | 2021-01-06 03:30:46 | timeout   |
| 3       | 2021-07-14 14:00:00 | timeout   |
| 7       | 2021-06-12 11:57:29 | confirmed |
| 7       | 2021-06-13 12:58:28 | confirmed |
| 7       | 2021-06-14 13:59:27 | confirmed |
| 2       | 2021-01-22 00:00:00 | confirmed |
| 2       | 2021-02-28 23:59:59 | timeout   |

Output: 

| user_id | confirmation_rate |
|---------|-------------------|
| 6       | 0.00              |
| 3       | 0.00              |
| 7       | 1.00              |
| 2       | 0.50              |

Explanation: \
User 6 did not request any confirmation messages. The confirmation rate is 0.\
User 3 made 2 requests and both timed out. The confirmation rate is 0.\
User 7 made 3 requests and all were confirmed. The confirmation rate is 1.\
User 2 made 2 requests where one was confirmed and the other timed out. The confirmation rate is 1 / 2 = 0.5.

In [1]:
signups = pd.DataFrame({'user_id' : [3, 7, 2, 6],
                        'time_stamp' : ['2020-03-21 10:16:13', '2020-01-04 13:57:59', '2020-07-29 23:09:44', '2020-12-09 10:39:37']
                       })

confirmations = pd.DataFrame({'user_id' : [3, 3, 7, 7, 7, 2, 2],
                              'time_stamp' : ['2021-01-06 03:30:46', '2021-07-14 14:00:00', '2021-06-12 11:57:29', '2021-06-13 12:58:28', '2021-06-14 13:59:27', '2021-01-22 00:00:00', '2021-02-28 23:59:59'],
                              'action' : ['timeout', 'timeout', 'confirmed', 'confirmed', 'confirmed', 'confirmed', 'timeout']
                             })

def cr(signups: pd.DataFrame, confirmations: pd.DataFrame) -> pd.DataFrame:
    df = signups[['user_id']].merge(confirmations[['user_id', 'action']], on='user_id', how='left')
    # print(df)
    df['action'] = df['action'].apply(lambda x: 1 if x == 'confirmed' else 0)
    print(df)
    df = df.groupby('user_id').sum() / df.groupby('user_id').count()
    print(df)
    df = df.reset_index()
    print(df)
    df = df.rename(columns = {'action' : 'confirmation rate'})
    return df 

cr(signups, confirmations)
